name: Update README

on:
  schedule:
    - cron: "0 06 * * 1"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  update-readme: 
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Update README
        run: date > README.md
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              git config --global user.name "${{ github.actor }}"
              git config --global user.email "${{ github.actor }}@users.noreply.github.com"
              git add README.md
              git commit -m "update release"
              git push origin main
